apiVersion: v2
name: petclinic-chart
description: A Helm chart for petclinic Application

type: application

version: 0.1.0

appVersion: "3.5.0"

dependencies:
  - name: mysql
    version: 9.4.0
    repository: https://charts.bitnami.com/bitnami
